# Generated by Django 6.0.1 on 2026-01-11 12:32

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('imap_server', models.CharField(default='imap.gmail.com', max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.CharField(db_index=True, max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('date', models.DateTimeField(db_index=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='api.emailaccount')),
            ],
            options={
                'verbose_name': 'Email',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('parkos', 'Parkos'), ('parkmundo', 'ParkMundo'), ('travelcar', 'TravelCar'), ('ector', 'Ector'), ('onepark', 'OnePark'), ('other', 'Autre')], db_index=True, max_length=50)),
                ('service_type', models.CharField(choices=[('parking', 'Parking'), ('hotel', 'Hôtel'), ('car_rental', 'Location voiture'), ('flight', 'Vol'), ('other', 'Autre')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmée'), ('pending', 'En attente'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='confirmed', max_length=50)),
                ('reservation_number', models.CharField(db_index=True, max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('extracted_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.email')),
            ],
            options={
                'verbose_name': 'Réservation Extraite',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True)),
                ('emails_fetched', models.IntegerField(default=0)),
                ('reservations_extracted', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('partial', 'Partiel')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration', models.FloatField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='api.emailaccount')),
            ],
            options={
                'verbose_name': 'Log de Synchronisation',
                'ordering': ['-sync_date'],
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['account', '-date'], name='api_email_account_0d3968_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sender', '-date'], name='api_email_sender_9305ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='extractedreservation',
            unique_together={('platform', 'reservation_number')},
        ),
    ]
