# Generated by Django 6.0.1 on 2026-01-11 13:30

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_options_alter_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='auth_type',
            field=models.CharField(choices=[('imap', 'IMAP (mot de passe)'), ('oauth_google', 'Google OAuth'), ('oauth_microsoft', 'Microsoft OAuth')], default='imap', max_length=20),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='oauth_tokens',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='imap_server',
            field=models.CharField(blank=True, default='imap.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
